//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetalWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Købstilbud
    {
        public int Id { get; set; }
        public int Pris { get; set; }
        public int SalgsudbudId { get; set; }
        public string KundeId { get; set; }
    
        public virtual Kunde Kunde { get; set; }
        public virtual Salgsudbud Salgsudbud { get; set; }
    }
}
